# Generated by Django 4.1 on 2022-08-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mokepon',
            field=models.CharField(default='', max_length=10),
        ),
    ]
