# Generated by Django 4.1 on 2022-08-28 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_mokepon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='mokepon',
        ),
        migrations.CreateModel(
            name='Mokepon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
    ]
