# Generated by Django 4.1 on 2022-08-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_player_mokepon_mokepon'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='posX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='posY',
            field=models.IntegerField(default=0),
        ),
    ]
