# Generated by Django 4.1 on 2022-08-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_posx_player_posy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('posX', models.IntegerField(default=0)),
                ('posY', models.IntegerField(default=0)),
                ('attack', models.CharField(default='', max_length=25)),
                ('type', models.CharField(default='', max_length=10)),
                ('hp', models.IntegerField(default=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Mokepon',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
