# Generated by Django 4.1 on 2022-09-03 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='attack',
        ),
        migrations.AddField(
            model_name='attack',
            name='damage',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='attack',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='attack',
            name='player_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.enemy'),
        ),
    ]
